# name: Build
# on:
#   push:
#     branches:
#       - master
#       - devops-class
#     paths:
#       - todo-app-backend/
#       - todo-app-frontend/
#   pull_request:
#     types: [opened, synchronize, reopened, closed]
#   workflow_dispatch:

# jobs:
#   sonarcloud:
#     name: Code analysis with SonarCloud
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#       - name: SonarCloud Scan
#         uses: SonarSource/sonarcloud-github-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#   detect-changes:
#     name: "Detect changes"
#     runs-on: ubuntu-latest
#     outputs:
#       dirs: ${{ steps.directories.outputs.all_changed_files }}
#       count: ${{ steps.directories.outputs.all_changed_files_count }}
#     steps:
#       - uses: actions/checkout@v4
#       - name: Get changed directories
#         id: directories
#         uses: tj-actions/changed-files@v40
#         with:
#           dir_names: true
#           json: true
#           escape_json: false
#           quotepath: false
#           files: |
#             todo-app-frontend/
#             todo-app-backend/
        
#   docker-build-and-push:
#     if: needs.detect-changes.outputs.count > 0
#     name: "Docker Build and Push"
#     runs-on: ubuntu-latest
#     needs: [detect-changes]
#     strategy:
#       matrix:
#         dir: ${{ fromJSON(needs.detect-changes.outputs.dirs) }}
#       max-parallel: 5
#       fail-fast: false

#     steps:
#       - run: echo ${{ matrix.dir }}
#       - uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Build Docker image
#         env:
#           GITHUB_SHA: ${{ github.sha }}
#         run: |
#           cd ./${{ matrix.dir }}
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dir }}:${GITHUB_SHA::5} .
          
#       - name: Push to Dockerhub
#         env:
#           GITHUB_SHA: ${{ github.sha }}
#         if: github.ref == 'refs/heads/master'
#         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dir }}:${GITHUB_SHA::5}


name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:

env:
  DOCKER_USERNAME: tomiwadevops

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_USERNAME }}/my-image
          tags: |
             type=sha

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./todo-app-frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true